-- Email Notification System Setup
-- Run this SQL in your Supabase SQL Editor

-- 1. Create email templates table
CREATE TABLE IF NOT EXISTS public.email_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  template_name text NOT NULL UNIQUE,
  subject text NOT NULL,
  html_content text NOT NULL,
  variables jsonb DEFAULT '{}',
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);

-- 2. Create email logs table
CREATE TABLE IF NOT EXISTS public.email_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  booking_id bigint REFERENCES public.bookings(id),
  recipient_email text NOT NULL,
  recipient_name text,
  template_name text NOT NULL,
  subject text NOT NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'bounced')),
  resend_id text, -- Resend email ID for tracking
  sent_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);

-- 3. Enable RLS on both tables
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
-- Email templates - admin can manage, users can read active templates
CREATE POLICY "Admins can manage email templates" ON public.email_templates
  FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');

CREATE POLICY "Anyone can read active email templates" ON public.email_templates
  FOR SELECT USING (is_active = true);

-- Email logs - users can see their own logs, admins can see all
CREATE POLICY "Users can view their own email logs" ON public.email_logs
  FOR SELECT USING (
    recipient_email = (SELECT email FROM auth.users WHERE id = auth.uid())
  );

CREATE POLICY "Admins can manage all email logs" ON public.email_logs
  FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');

-- 5. Grant permissions
GRANT SELECT, INSERT ON public.email_templates TO authenticated;
GRANT SELECT, INSERT ON public.email_logs TO authenticated;
GRANT ALL ON public.email_templates TO service_role;
GRANT ALL ON public.email_logs TO service_role;

-- 6. Insert default email templates
INSERT INTO public.email_templates (template_name, subject, html_content, variables) VALUES

-- Order Confirmed Template
('order_confirmed', 
'✅ Your SparklePro cleaning is confirmed - Booking #{{booking_number}}',
'<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Confirmed</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #10b981, #059669); color: white; padding: 30px; text-align: center; border-radius: 12px 12px 0 0; }
        .content { background: #f9fafb; padding: 30px; }
        .booking-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #10b981; }
        .footer { background: #374151; color: white; padding: 20px; text-align: center; border-radius: 0 0 12px 12px; }
        .button { background: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold; }
        .highlight { color: #10b981; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎉 Booking Confirmed!</h1>
        <p>Your SparklePro cleaning service is scheduled</p>
    </div>
    
    <div class="content">
        <p>Hello <strong>{{customer_name}}</strong>,</p>
        
        <p>Great news! Your cleaning service has been confirmed. Our professional cleaning team is ready to make your space sparkle! ✨</p>
        
        <div class="booking-details">
            <h3>📋 Booking Details</h3>
            <p><strong>Booking Number:</strong> <span class="highlight">#{{booking_number}}</span></p>
            <p><strong>Service:</strong> {{service_name}}</p>
            <p><strong>Date & Time:</strong> {{service_date}} at {{service_time}}</p>
            <p><strong>Address:</strong> {{service_address}}</p>
            <p><strong>Total Amount:</strong> <span class="highlight">{{total_amount}} AED</span></p>
        </div>
        
        <h3>📞 What''s Next?</h3>
        <ul>
            <li>Our team will call you 30 minutes before arrival</li>
            <li>Please ensure someone is available to provide access</li>
            <li>Any special instructions? Reply to this email!</li>
        </ul>
        
        <p style="text-align: center; margin: 30px 0;">
            <a href="{{app_url}}/history" class="button">View Booking Details</a>
        </p>
    </div>
    
    <div class="footer">
        <p><strong>SparklePro</strong> - Professional Cleaning Services</p>
        <p>📧 sparkleproapp@gmail.com | 📱 WhatsApp Support</p>
        <p>Need help? Reply to this email anytime!</p>
    </div>
</body>
</html>',
'{"booking_number": "text", "customer_name": "text", "service_name": "text", "service_date": "text", "service_time": "text", "service_address": "text", "total_amount": "number", "app_url": "text"}'
),

-- Order In Progress Template  
('order_in_progress',
'🧹 Your cleaner is on the way - Booking #{{booking_number}}',
'<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cleaner On The Way</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #3b82f6, #1d4ed8); color: white; padding: 30px; text-align: center; border-radius: 12px 12px 0 0; }
        .content { background: #f9fafb; padding: 30px; }
        .status-box { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #3b82f6; }
        .footer { background: #374151; color: white; padding: 20px; text-align: center; border-radius: 0 0 12px 12px; }
        .highlight { color: #3b82f6; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚗 Cleaner On The Way!</h1>
        <p>Your SparklePro team is heading to you</p>
    </div>
    
    <div class="content">
        <p>Hello <strong>{{customer_name}}</strong>,</p>
        
        <p>Exciting news! Your cleaning team has started their journey to your location. They should arrive within the scheduled time window.</p>
        
        <div class="status-box">
            <h3>📍 Current Status</h3>
            <p><strong>Booking #:</strong> <span class="highlight">{{booking_number}}</span></p>
            <p><strong>Status:</strong> <span class="highlight">In Progress - Team Dispatched</span></p>
            <p><strong>Expected Arrival:</strong> {{service_time}}</p>
            <p><strong>Service Address:</strong> {{service_address}}</p>
        </div>
        
        <h3>📋 Please Ensure:</h3>
        <ul>
            <li>✅ Someone is available to provide access</li>
            <li>✅ Clear pathways for our cleaning team</li>
            <li>✅ Secure any valuable or fragile items</li>
            <li>✅ Your phone is available for team communication</li>
        </ul>
        
        <p><strong>Questions?</strong> Feel free to reply to this email or contact our support team!</p>
    </div>
    
    <div class="footer">
        <p><strong>SparklePro</strong> - Professional Cleaning Services</p>
        <p>📧 sparkleproapp@gmail.com | 📱 WhatsApp Support</p>
    </div>
</body>
</html>',
'{"booking_number": "text", "customer_name": "text", "service_time": "text", "service_address": "text"}'
),

-- Order Completed Template
('order_completed',
'✨ Cleaning completed! Please share your experience - Booking #{{booking_number}}',
'<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cleaning Completed</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #10b981, #059669); color: white; padding: 30px; text-align: center; border-radius: 12px 12px 0 0; }
        .content { background: #f9fafb; padding: 30px; }
        .completion-box { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #10b981; }
        .footer { background: #374151; color: white; padding: 20px; text-align: center; border-radius: 0 0 12px 12px; }
        .button { background: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold; margin: 5px; }
        .button-secondary { background: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold; margin: 5px; }
        .highlight { color: #10b981; font-weight: bold; }
        .stars { font-size: 24px; color: #fbbf24; }
    </style>
</head>
<body>
    <div class="header">
        <h1>✨ Cleaning Completed!</h1>
        <p>Your space is now sparkling clean</p>
    </div>
    
    <div class="content">
        <p>Hello <strong>{{customer_name}}</strong>,</p>
        
        <p>Fantastic! Our cleaning team has completed your service. We hope you love your freshly cleaned space! 🏠✨</p>
        
        <div class="completion-box">
            <h3>📋 Service Summary</h3>
            <p><strong>Booking #:</strong> <span class="highlight">{{booking_number}}</span></p>
            <p><strong>Service:</strong> {{service_name}}</p>
            <p><strong>Completed:</strong> {{completion_time}}</p>
            <p><strong>Duration:</strong> {{service_duration}}</p>
        </div>
        
        <h3>⭐ How was your experience?</h3>
        <p>Your feedback helps us improve and helps other customers choose SparklePro. Please take a moment to share your experience:</p>
        
        <div style="text-align: center; margin: 30px 0;">
            <div class="stars">⭐⭐⭐⭐⭐</div>
            <br>
            <a href="{{app_url}}/review?booking={{booking_id}}" class="button">Leave a Review</a>
            <a href="{{app_url}}/book" class="button-secondary">Book Again</a>
        </div>
        
        <h3>🔁 Loved our service?</h3>
        <ul>
            <li>📅 <strong>Schedule regular cleaning</strong> - Save time with recurring bookings</li>
            <li>👨‍👩‍👧‍👦 <strong>Refer friends & family</strong> - They''ll love SparklePro too!</li>
            <li>💬 <strong>Follow us</strong> for cleaning tips and special offers</li>
        </ul>
    </div>
    
    <div class="footer">
        <p><strong>SparklePro</strong> - Professional Cleaning Services</p>
        <p>📧 sparkleproapp@gmail.com | 📱 WhatsApp Support</p>
        <p>Thank you for choosing SparklePro! 💚</p>
    </div>
</body>
</html>',
'{"booking_number": "text", "customer_name": "text", "service_name": "text", "completion_time": "text", "service_duration": "text", "booking_id": "text", "app_url": "text"}'
),

-- Order Cancelled Template
('order_cancelled',
'❌ Booking cancellation confirmed - #{{booking_number}}',
'<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Cancelled</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #ef4444, #dc2626); color: white; padding: 30px; text-align: center; border-radius: 12px 12px 0 0; }
        .content { background: #f9fafb; padding: 30px; }
        .cancellation-box { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ef4444; }
        .footer { background: #374151; color: white; padding: 20px; text-align: center; border-radius: 0 0 12px 12px; }
        .button { background: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold; }
        .highlight { color: #ef4444; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 Booking Cancelled</h1>
        <p>Your cancellation has been processed</p>
    </div>
    
    <div class="content">
        <p>Hello <strong>{{customer_name}}</strong>,</p>
        
        <p>We''ve successfully cancelled your booking as requested. We''re sorry we won''t be able to serve you this time, but we hope to see you again soon!</p>
        
        <div class="cancellation-box">
            <h3>📋 Cancellation Details</h3>
            <p><strong>Booking #:</strong> <span class="highlight">{{booking_number}}</span></p>
            <p><strong>Service:</strong> {{service_name}}</p>
            <p><strong>Original Date:</strong> {{service_date}} at {{service_time}}</p>
            <p><strong>Cancelled:</strong> {{cancellation_time}}</p>
            {{#if refund_amount}}
            <p><strong>Refund Amount:</strong> <span class="highlight">{{refund_amount}} AED</span></p>
            <p><em>Refund will be processed within 3-5 business days</em></p>
            {{/if}}
        </div>
        
        <h3>😔 We''d love your feedback</h3>
        <p>If there''s anything we could have done better, please let us know by replying to this email. Your feedback helps us improve our service.</p>
        
        <h3>🔄 Ready to book again?</h3>
        <p>We''re here whenever you need professional cleaning services:</p>
        
        <div style="text-align: center; margin: 30px 0;">
            <a href="{{app_url}}/book" class="button">Book New Service</a>
        </div>
    </div>
    
    <div class="footer">
        <p><strong>SparklePro</strong> - Professional Cleaning Services</p>
        <p>📧 sparkleproapp@gmail.com | 📱 WhatsApp Support</p>
        <p>We hope to serve you again soon! 💚</p>
    </div>
</body>
</html>',
'{"booking_number": "text", "customer_name": "text", "service_name": "text", "service_date": "text", "service_time": "text", "cancellation_time": "text", "refund_amount": "number", "app_url": "text"}'
);

RAISE NOTICE 'Email notification system tables and templates created successfully!';
